### ISSUE TITLE
Can't determine your hostname!

### ISSUE THREAD

**Issue by x-one** [agcorreatech/tetrinetx_modern#1]
I've just wanted run tetrinetx on my server to play with my friends but no metter what i've do I still getting "Can't determine your hostname!"

**Comment by agcorreatech** [comment]
Hi! Sorry for the delay in responding. Could you please provide more information to reproduce the issue? I tryed here and the server was started successfully in Ubuntu Linux. No additional configuration needed.

**Comment by agcorreatech** [comment]
Thanks for reporting this, and sorry it took me a while to identify the root cause :)

I finally tracked down the issue and published a fix in the develop branch.

Root cause: the getmyhostname() function (src/net.c) called fatal() (exit(1)) whenever it couldn't resolve a fully qualified hostname (one containing a domain name) for the local machine. This is actually a common situation in containers, sandboxes, and systems without proper DNS configuration. As a result, what was essentially a cosmetic hostname resolution issue caused the entire server to terminate during startup.

Fix: instead of aborting the process, the server now falls back to the best hostname it can determine (first from the HOSTNAME environment variable, then from gethostname(), and finally to "localhost" if necessary). It logs a warning (both to the console and game.log) and continues starting normally.

This should allow TetriNETX to run correctly even in environments where a fully qualified hostname cannot be resolved.
